# Generated by Django 6.0.4 on 2026-04-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='author',
            new_name='Summary',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
    ]
