# Generated by Django 6.0.4 on 2026-05-08 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_logs', '0003_rename_author_entry_summary_remove_entry_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='Book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Book_logs.book'),
        ),
    ]
